### ISSUE TITLE
unable to run the script

### ISSUE THREAD

**Issue by Rakeshcool** [yanyiju/twixtor-batch-operation-script#1]
while trying to run the script i am getting this error: 
unable to execute script at line 347.Function ids.map is undefined.
I have tried to run this scripts on different clips but still getting the same error.
![yoho](https://user-images.githubusercontent.com/13606826/159150862-aca9753a-cd9d-4923-a6ea-ddcd9e0aada1.JPG)

**Comment by yanyiju** [comment]
Hey @Rakeshcool , thanks for your feedback. Could you share me how you tried to run the script?

Here are my steps for your reference and the script can still run successfully on my mac for cc2020.
1. Import your source video and create a comp over it (I name the comp as "test").
<img width="1440" alt="截屏2022-03-19 下午11 53 38" src="https://user-images.githubusercontent.com/35549199/159151967-89f940f4-d3b6-45a7-b7c5-40a2fd0cf43e.png">
<img width="1440" alt="截屏2022-03-19 下午11 54 37" src="https://user-images.githubusercontent.com/35549199/159151988-22b27f9b-ed1d-491c-bad2-1ca10f5352a7.png">

2. Open the comp and then open the script from file > scripts > twixtor-batch-operation-script.jsx. The panel will display the comp you are in at the moment.
<img width="1440" alt="截屏2022-03-19 下午11 56 17" src="https://user-images.githubusercontent.com/35549199/159152020-c45349bb-3d5a-4053-a499-a9a2c3e33f57.png">

3. Then I check "Select all video layers" (optional step) and click "Here we go!!!". After a very short time, the script will create the whole comp structure for you. The original comp ("test" in my case) won't be modified, instead, a new comp with "_script" suffix ("test_script" in my case) will be created for you.
<img width="1440" alt="截屏2022-03-19 下午11 56 32" src="https://user-images.githubusercontent.com/35549199/159152098-d8ccc6fa-e0eb-4ee9-a9d4-72e76589a5da.png">
<img width="1440" alt="截屏2022-03-19 下午11 59 17" src="https://user-images.githubusercontent.com/35549199/159152125-71d4888b-acc5-4cdb-9433-75eeda99c609.png">

4. Open the first-layer precomp of the source video, and you will see Twixtor plugin has already been applied.
<img width="1440" alt="截屏2022-03-20 上午12 20 57" src="https://user-images.githubusercontent.com/35549199/159152480-060abe1c-9877-4196-8bc5-b313072cf960.png">

**Comment by Rakeshcool** [comment]
hello  @ yanyiju <https://github.com/yanyiju>   san
thanks for responding in such a  short notice
so my specs are:adobe after effects 2020 on a windows machine
[image: 1.JPG]
[image: 2.JPG]
[image: 3.JPG]

so as you can see i am getting this issue while trying to run the script
i have all the methods to run the script but for some reason it is getting
stuck at that point,can you please figure out what I might be doing wrong?
or is it come coding error😅

**Comment by yanyiju** [comment]
Hey @Rakeshcool , I can not see your screenshot. Could you update?

**Comment by Rakeshcool** [comment]
[image: 1.JPG][image: 2.JPG][image: 3.JPG]
i have added photos again as well as zipped them in case if it is still not
visible

**Comment by yanyiju** [comment]
If possible, please paste the pic directly on your [#github issue page](https://github.com/yanyiju/twixtor-batch-operation-script/issues/1) instead of email. :) Otherwise, I can never see them.

**Comment by Rakeshcool** [comment]
all right i am doing it right away

**Comment by Rakeshcool** [comment]
![1](https://user-images.githubusercontent.com/13606826/159153172-47c08d04-612f-4eba-a5d5-498323196da6.JPG)
![2](https://user-images.githubusercontent.com/13606826/159153174-accb3357-1caa-469d-afbf-8ad0753f536b.JPG)
![3](https://user-images.githubusercontent.com/13606826/159153176-b6cd0a2a-4175-45bc-90bf-743ecafe3396.JPG)

**Comment by yanyiju** [comment]
Hey @Rakeshcool , I suppose I know the reason. It should be an issue about AE ExtendScript - despite that the coding language is based on JavaScript, some source functions (like the map function related to your error message) in JavaScript may not be supported. Not sure about difference between our ExtendScript versions, but I have updated a new version of the script to avoid using such JS functions. Please download and try again. Thanks again for your feedback.

**Comment by Rakeshcool** [comment]
yeah it is working now thanks for fixing the issue.
